from functools import lru_cache
from pathlib import Path

from pydantic import Field, SecretStr
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_prefix="OWNCHART_",
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    env: str = Field(default="dev", description="dev | prod")
    debug_payloads: bool = Field(
        default=False,
        description="If True, raw request/response bodies may be logged. PHI risk.",
    )

    database_url: str = Field(
        default="postgresql+asyncpg://ownchart:ownchart@postgres:5432/ownchart"
    )
    redis_url: str = Field(default="redis://redis:6379/0")

    session_secret: SecretStr = Field(
        default=SecretStr("change-me-in-env"),
        description="Used to sign httpOnly session cookies. Set in infra/.env.",
    )
    session_cookie_name: str = "ownchart_session"
    session_max_age_seconds: int = 60 * 60 * 24 * 14

    data_dir: Path = Field(default=Path("/data"))

    anthropic_api_key: SecretStr | None = Field(default=None)
    anthropic_default_model: str = Field(default="claude-opus-4-7")
    anthropic_vision_model: str = Field(default="claude-opus-4-7")

    # AES-256 data encryption key (base64 32-byte). Used to encrypt OAuth
    # access/refresh tokens at rest. Generated by deploy.sh on first deploy
    # and persisted in infra/.env. Treat as more sensitive than session_secret —
    # losing it means re-authenticating every connected provider.
    token_dek: SecretStr | None = Field(default=None)

    # Public base URL used to compose redirect_uris registered with EHRs.
    # Must match what's on file with the provider (e.g. fhir.epic.com app reg).
    # Override with OWNCHART_PUBLIC_BASE_URL on every real deployment.
    public_base_url: str = Field(default="http://localhost:8080")

    # Bearer token for the Health Auto Export iOS app's REST push
    # endpoint. Configure both: (a) here in infra/.env, (b) in the iOS
    # app's Automations → REST API setup, with the same value as the
    # Authorization header. When unset, the push endpoint returns 503
    # so it's not silently open. Single-tenant V1 — multi-user deploys
    # will want per-user tokens instead.
    auto_export_token: SecretStr | None = Field(default=None)

    cors_allow_origins: list[str] = Field(default_factory=list)

    # Demo mode (demo.ownchart.me). When True, the API rejects every
    # mutating request (POST / PATCH / PUT / DELETE) outside the
    # allowlist with HTTP 403. Lets us run a public read-only
    # instance against the Epic FHIR sandbox without risk of writes.
    # Pairs with a visible "Demo · sample data" banner on the web.
    demo_mode: bool = Field(default=False)
    # Demo seed credentials. Public on purpose — the demo instance is
    # designed for anonymous read-only browsing. Don't ever turn these
    # into real PHI accounts.
    demo_user_email: str = Field(default="demo@ownchart.me")
    demo_user_password: SecretStr = Field(default=SecretStr("MYHEALTHdata"))


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    return Settings()
